### ISSUE TITLE
 deploy error: 

### ISSUE THREAD

**Issue by rectinajh** [Jeiwan/zuniswap#1]
when i decide deploy the contract.

npx hardhat run scripts/deploy.js

can help me solve the problem

`Error: missing argument:  in Contract constructor (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=contracts/5.4.1)
    at Logger.makeError (/Users/a212/Desktop/zuniswap/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/Users/a212/Desktop/zuniswap/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Logger.checkArgumentCount (/Users/a212/Desktop/zuniswap/node_modules/@ethersproject/logger/src.ts/index.ts:284:18)
    at ContractFactory.<anonymous> (/Users/a212/Desktop/zuniswap/node_modules/@ethersproject/contracts/src.ts/index.ts:1201:16)
    at step (/Users/a212/Desktop/zuniswap/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/a212/Desktop/zuniswap/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at /Users/a212/Desktop/zuniswap/node_modules/@ethersproject/contracts/lib/index.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/a212/Desktop/zuniswap/node_modules/@ethersproject/contracts/lib/index.js:19:12)
    at ContractFactory.deploy (/Users/a212/Desktop/zuniswap/node_modules/@ethersproject/contracts/lib/index.js:1111:16) {
  reason: 'missing argument:  in Contract constructor',
  code: 'MISSING_ARGUMENT',
  count: 0,
  expectedCount: 1
}
`

**Comment by Jeiwan** [comment]
Thanks for reporting! Here's a fix: https://github.com/Jeiwan/zuniswap/commit/ac16ce676acd2b051b21239d74b2f42cf9b560e7
